name: Run Tests Python 3.10 v2

on:
  push:
    branches:
      - v2

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image with Python 3.1
      run: docker build -t python3.1-env .

    - name: Run tests in Docker
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      run: |
        docker run -v $(pwd):/app -w /app python3.1-env bash -c "
          python3.1 -m pip install --upgrade pip &&
          python3.1 -m pip install -r v2/requirements.txt &&
          cd v2 && python3.1 -m pytest tests/
        "
